// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	entity "aggregator/internal/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// AggregatorUseCase is an autogenerated mock type for the AggregatorUseCase type
type AggregatorUseCase struct {
	mock.Mock
}

// GetStats provides a mock function with given fields: ctx, from, to
func (_m *AggregatorUseCase) GetStats(ctx context.Context, from time.Time, to time.Time) ([]entity.NewUsersAndCardsStats, error) {
	ret := _m.Called(ctx, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 []entity.NewUsersAndCardsStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) ([]entity.NewUsersAndCardsStats, error)); ok {
		return rf(ctx, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) []entity.NewUsersAndCardsStats); ok {
		r0 = rf(ctx, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.NewUsersAndCardsStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAggregatorUseCase creates a new instance of AggregatorUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAggregatorUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *AggregatorUseCase {
	mock := &AggregatorUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
