// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Cache is an autogenerated mock type for the Cache type
type Cache struct {
	mock.Mock
}

// GetOrSet provides a mock function with given fields: ctx, key, fetchFunc
func (_m *Cache) GetOrSet(ctx context.Context, key string, fetchFunc func() (interface{}, error)) (interface{}, error) {
	ret := _m.Called(ctx, key, fetchFunc)

	if len(ret) == 0 {
		panic("no return value specified for GetOrSet")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, func() (interface{}, error)) (interface{}, error)); ok {
		return rf(ctx, key, fetchFunc)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, func() (interface{}, error)) interface{}); ok {
		r0 = rf(ctx, key, fetchFunc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, func() (interface{}, error)) error); ok {
		r1 = rf(ctx, key, fetchFunc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCache creates a new instance of Cache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cache {
	mock := &Cache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
