// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "todo/internal/entity"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// TodoUseCase is an autogenerated mock type for the TodoUseCase type
type TodoUseCase struct {
	mock.Mock
}

// CreateBoard provides a mock function with given fields: ctx, board
func (_m *TodoUseCase) CreateBoard(ctx context.Context, board *entity.Board) error {
	ret := _m.Called(ctx, board)

	if len(ret) == 0 {
		panic("no return value specified for CreateBoard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Board) error); ok {
		r0 = rf(ctx, board)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateCard provides a mock function with given fields: ctx, card
func (_m *TodoUseCase) CreateCard(ctx context.Context, card *entity.Card) error {
	ret := _m.Called(ctx, card)

	if len(ret) == 0 {
		panic("no return value specified for CreateCard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Card) error); ok {
		r0 = rf(ctx, card)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateColumn provides a mock function with given fields: ctx, column
func (_m *TodoUseCase) CreateColumn(ctx context.Context, column *entity.Column) error {
	ret := _m.Called(ctx, column)

	if len(ret) == 0 {
		panic("no return value specified for CreateColumn")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Column) error); ok {
		r0 = rf(ctx, column)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteBoard provides a mock function with given fields: ctx, id
func (_m *TodoUseCase) DeleteBoard(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBoard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCard provides a mock function with given fields: ctx, id
func (_m *TodoUseCase) DeleteCard(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteColumn provides a mock function with given fields: ctx, id
func (_m *TodoUseCase) DeleteColumn(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteColumn")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBoardByID provides a mock function with given fields: ctx, id
func (_m *TodoUseCase) GetBoardByID(ctx context.Context, id uuid.UUID) (*entity.Board, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBoardByID")
	}

	var r0 *entity.Board
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Board, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Board); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Board)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBoardsByUser provides a mock function with given fields: ctx, userID, limit, offset
func (_m *TodoUseCase) GetBoardsByUser(ctx context.Context, userID uuid.UUID, limit int, offset int) ([]entity.Board, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetBoardsByUser")
	}

	var r0 []entity.Board
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]entity.Board, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []entity.Board); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Board)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCardByID provides a mock function with given fields: ctx, id
func (_m *TodoUseCase) GetCardByID(ctx context.Context, id uuid.UUID) (*entity.Card, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCardByID")
	}

	var r0 *entity.Card
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Card, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Card); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Card)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCardsByColumn provides a mock function with given fields: ctx, columnID, limit, offset
func (_m *TodoUseCase) GetCardsByColumn(ctx context.Context, columnID uuid.UUID, limit int, offset int) ([]entity.Card, error) {
	ret := _m.Called(ctx, columnID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetCardsByColumn")
	}

	var r0 []entity.Card
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]entity.Card, error)); ok {
		return rf(ctx, columnID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []entity.Card); ok {
		r0 = rf(ctx, columnID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Card)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, columnID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetColumnByID provides a mock function with given fields: ctx, id
func (_m *TodoUseCase) GetColumnByID(ctx context.Context, id uuid.UUID) (*entity.Column, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetColumnByID")
	}

	var r0 *entity.Column
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Column, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Column); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Column)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetColumnsByBoard provides a mock function with given fields: ctx, boardID, limit, offset
func (_m *TodoUseCase) GetColumnsByBoard(ctx context.Context, boardID uuid.UUID, limit int, offset int) ([]entity.Column, error) {
	ret := _m.Called(ctx, boardID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetColumnsByBoard")
	}

	var r0 []entity.Column
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]entity.Column, error)); ok {
		return rf(ctx, boardID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []entity.Column); ok {
		r0 = rf(ctx, boardID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Column)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, boardID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNewCards provides a mock function with given fields: ctx, from, to
func (_m *TodoUseCase) GetNewCards(ctx context.Context, from time.Time, to time.Time) ([]entity.Card, error) {
	ret := _m.Called(ctx, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetNewCards")
	}

	var r0 []entity.Card
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) ([]entity.Card, error)); ok {
		return rf(ctx, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) []entity.Card); ok {
		r0 = rf(ctx, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Card)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBoard provides a mock function with given fields: ctx, board
func (_m *TodoUseCase) UpdateBoard(ctx context.Context, board *entity.Board) error {
	ret := _m.Called(ctx, board)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBoard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Board) error); ok {
		r0 = rf(ctx, board)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateCard provides a mock function with given fields: ctx, card
func (_m *TodoUseCase) UpdateCard(ctx context.Context, card *entity.Card) error {
	ret := _m.Called(ctx, card)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Card) error); ok {
		r0 = rf(ctx, card)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateColumn provides a mock function with given fields: ctx, column
func (_m *TodoUseCase) UpdateColumn(ctx context.Context, column *entity.Column) error {
	ret := _m.Called(ctx, column)

	if len(ret) == 0 {
		panic("no return value specified for UpdateColumn")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Column) error); ok {
		r0 = rf(ctx, column)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTodoUseCase creates a new instance of TodoUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTodoUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *TodoUseCase {
	mock := &TodoUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
